### ISSUE TITLE
No support for normal selection

### ISSUE THREAD

**Issue by jonathan-nielsen** [earshinov/vscode-sort-lines-by-selection#1]
When you select by multiple cursors (like shown in the example) this works as expected, but if you drag-select text and hit the sort button, nothing happens. Is this by design or a bug? I'm guessing it's a bug since you wrap this extension around the sublime text sort package and I just tried that out and it works when you select by dragging as well.

OS: MacOS Mojave 10.14.6
VSCode version: 1.42.0
Sort Lines by Selection version: 1.0.0

**Comment by earshinov** [comment]
Hi! Are we talking about the same SublimeText extension, https://packagecontrol.io/packages/Sort%20Lines%20By%20Selection ? It does not seem to fire for single selection for me. For example:

```
import { DataFilterPipe } from 'app/pipe[[[s/data-filter.pipe';
import { NestedValuePipe } from 'app/pipes/nested-value.pipe';
import { AuthService } from 'app/core/service/auth/auth.service';
import { PageVisibilityService } from 'app/service/page-visibility.service';
import { downloadBlob } from 'app/utils/dom';
import { UnixTimePipe } from 'app/pipes/unixtime-to-date.pipe';
import { ModalService } from 'app/serv]]]ice/modal.service';
```

I have marked selection with `[[[...]]]`. When I choose 'Sort Lines by Selection' in SublimeText's command palette (Ctrl-Shift-P), nothing happens.

I must say that I don't see much sense in using 'Sort Lines by Selection' when selection spans entire lines. One might as well use the 'Sort Lines Ascending' command built into VS Code (`editor.action.sortLinesAscending`).

**Comment by Zorkeel** [comment]
Hello, I don't know about the other extensions but what I expect as a user without any prior experience is:
(using sortLinesBySelection)
- multiple selections: sort the selections
- one selection of multiple lines: sort the lines

This way it allows us to do both cases using only one shortcut.

Great extension, I just discovered it.

**Comment by coderfin** [comment]
Awesome extension, thanks @earshinov!  The `morph` feature is amazing and just what I needed to ignore dashes when sorting.

I do wish that `v1.2.0` was published to the marketplace.  @Zorkeel is right that I expected to select once but sort each line.  `v1.2.0` accomplishes this.  I also like the `natural_sort` feature.

For future visitors, I was able to take the following steps to manually compile and install the `v1.2.0` extension:

1. Run `yarn install -g @vscode/vsce`
  1.1. Used to compile the extension into a `.vsix` file
2. Clone the repo
  2.1. ie. `git clone git@github.com:earshinov/vscode-sort-lines-by-selection.git`
3. Run `yarn install` in the repo root directory
4. Run `yarn compile`
  4.1. Make sure everything is compiling fine
5. Run  `vsce package` in the repo root directory
  5.1. Creates the `.vsix` file
6. In vscode select to `Install from VSIX...`
  6.1. 
<img width="630" alt="Screenshot 2023-03-13 at 11 01 10 PM" src="https://user-images.githubusercontent.com/1514172/224897886-1362acb4-eba9-4482-bbb8-a549ccc8ad1e.png">

7. Setup your keyboard shortcut
  7.1. In my case ignore non-alphanumeric
```
{
  "key": "f9",
  "command": "sort-lines-by-selection.sortLinesBySelection",
  "natural_sort": true,
  "args": {
    "morph": "s.replace(/[^a-zA-Z0-9]/g, '')"
  }
}
```
8. Sort your lines using a single selection!
  8.1. 
![sort](https://user-images.githubusercontent.com/1514172/224900077-c9ed41b7-511e-487d-b5e6-569c4957452d.gif)

**Comment by earshinov** [comment]
Hi @coderfin, and thank you for an elaborate comment. I am back from vacation and will publish version 1.2.0 soon

**Comment by earshinov** [comment]
Version 1.2.0 is published, feel free to check it out. Closing this issue as resolved.

**Comment by coderfin** [comment]
> Version 1.2.0 is published, feel free to check it out. Closing this issue as resolved.

Just installed from the official marketplace and tested it. It works great!  Thank you!
